site_name: RibaFS Portal
site_url: https://ribafs.github.io
site_description: Portal do Ribamar FS
site_author: Ribamar FS
site_dir: site/

repo_url: https://github.com/ribafs//ribafs.github.io

docs_dir: docs/

extra_css:
    - assets/css/extra.css
extra_javascript:
#    - assets/js/script.js

theme:
    name: darkly
    custom_dir: docs/overrides
    favicon: img/favicon.ico
    highlightjs: true
    hljs_languages:
        - php
        - html

markdown_extensions:
  markdown.extensions.codehilite:
    css_class: highlight
    pymdownx.highlight:
      guess_lang: false
      linenums: true    

plugins:
    - search:
        indexing: full

nav:
    - Início: index.md
    - Front-end:
        #- HTML:
        #    - Introdução: frontend/html/index.md        
        - HTML 5:
            - Dicas: frontend/html/html5/dicas.md
            - Inputs e atributos: frontend/html/html5/inputs.md
            - CSS3 para o HTML 5: frontend/html/html5/css.md
            - Tags semânticas: frontend/html/html5/semanticas.md
            - Validação: frontend/html/html5/pattern-validation/dist/index.html
            - Regex: frontend/html/html5/regex.md
        #- CSS:
        #    - Introdução: frontend/css/index.md
        - JavaScript:
        #    - Introdução: frontend/js/index.md
            - Muito conteúdo: https://ribafs.github.io/javascript
            - Método Reduce : frontend/js/reduce.md
    - Back-end:
        - Linguagens: backend/linguagens.md
        - PHP: 
            - Expressões Regulares: backend/php/regex.md
            - Trabalhando com URL: backend/php/url.md            
            - Valor default em select: backend/php/select-default-value.md
            - Brincando com arrays múltiplos: backend/php/arrays-multiplos.md
        #- PDO: 
        #    - Introdução: backend/pdo/index.md
        - PHP-OO: 
            #- Introdução: backend/phpoo/index.md
            - MVC: 
                #- Introdução: backend/phpoo/mvc/index.md
                - Framework do zero: backend/phpoo/mvc/fw-zero.md
                - Rotas simples: backend/phpoo/mvc/php-router.md
                - Simplest Router: backend/phpoo/mvc/simplest-router.md
                - Micro Framework: backend/phpoo/mvc/micro-framework.md
        - Framework:
            - Laravel: 
                - Gerador de API CRUD para Laravel 9: backend/framework/laravel/gerador-laravel.md
                - Migrations e Seeders no Laravel 9: backend/framework/laravel/migrations-seeders.md
                - Gerador de CRUDs no Laravel 9: backend/framework/laravel/crud-generator.md
                - Crud Generator on Laravel 9 (english): backend/framework/laravel/crud-generator-en.md
                - Tratamento de exceções no Laravel 9: backend/framework/laravel/error-handler.md
        #    - Codeigniter: 
        #        - Introdução: backend/framework/ci/index.md

    - DevOps:
        - Apache:
            - .htaccess: devops/apache/htaccess.md

    - Linux:
        - Introdução: linux/index.md
        - Diferenças Linux x Windows: linux/linuxwindows.md
    - Reflexões:
        - Iniciante X Versões: reflexoes/versoes.md

    - Ferramentas:
        - Hospedagem Grátis: ferramentas/hosting-free.md
        #- HTML Live: ferramentas/html-live/index.html
        - MkDocs: https://github.com/ribafs/mkdocs-ribafs
        - Recursos Gratuitos: https://github.com/ribafs/gratuitos
        - Live Chat: ferramentas/live-chat.md
    - Sobre: 
        - Currículo: sobre/curriculo.md
        - Repositórios: https://github.com/ribafs/alguns-repos
        - Livros free: sobre/livros.md
        - Contato: sobre/contato.md
        
    - Comentários: comments.md

#    - Mapa do site: mapa.md

